client_config_backend: settings
client_config:
client_id: 295183743500-914t8k7guqkl1e1rv5g4o3m1ugppul2j.apps.googleusercontent.com
client_secret: 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
save_credentials: True
save_credentials_file: credentials.json
save_credentials_backend: file
oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive